---
title: "VizforCovid"
output: pdf_document
---

#Run all chunks in AutomatingCode.rmd before running anything in this file. It will not work if you don't. 
```{r}
daily$DATE = as.Date(daily$DATE, "%Y-%m-%d")
ggplot(data = daily, aes(x = DATE, y = CASES_NEW), lwd=2) + geom_line(color= 'red') + theme(axis.text.x = element_text(angle = 90), legend.direction = 'horizontal', legend.position = 'bottom') + ylab("Daily New Cases") + scale_x_date(date_labels="%b %d",date_breaks  ="1 week") + ylim(0,100) + ggtitle("Daily New Cases in Hamilton County")

ggplot(data = daily, aes(x = DATE, y = CASES_NEW_LAST7DAYS), lwd=2) + geom_line(color= 'red') + theme(axis.text.x = element_text(angle = 90), legend.direction = 'horizontal', legend.position = 'bottom') + ylab("Daily New Cases, Last Seven Days") + scale_x_date(date_labels="%b %d",date_breaks  ="1 week") + ylim(0,500) + ggtitle("Daily New Cases for Last Seven Days in Hamilton County")

daily$CASES_TOTAL = gsub( ",", "", as.character(daily$CASES_TOTAL))
test = as.numeric(daily$CASES_TOTAL)
daily$CASES_TOTAL = test
ggplot(data = daily, aes(x = DATE, y = CASES_TOTAL), lwd=2) + geom_line(color= 'red') + theme(axis.text.x = element_text(angle = 90), legend.direction = 'horizontal', legend.position = 'bottom') + ylab("Total Cases") + scale_x_date(date_labels="%b %d",date_breaks  ="1 week") + ylim(0,1500) + ggtitle("Total Cases in Hamilton County")


daily$CASES_GROWTHRATE = gsub( "%", "", as.character(daily$CASES_GROWTHRATE))
daily$CASES_GROWTHRATE = as.numeric(daily$CASES_GROWTHRATE)
ggplot(data = daily, aes(x = DATE, y = CASES_GROWTHRATE), lwd=2) + geom_line(color= 'red') + theme(axis.text.x = element_text(angle = 90), legend.direction = 'horizontal', legend.position = 'bottom')  + ylab("Growth Rate of Cases") +  scale_x_date(date_labels="%b %d",date_breaks  ="1 week") + ggtitle("Covid Growth Rate in Hamilton County")
```


```{r}
# countytable = countytable[which(!countytable$COUNTY == 'Out of State'),]
ham = countytable[which(countytable$COUNTY == 'Hamilton'),]
ham = ham[complete.cases(ham$TOTAL_TESTS),]

ham$DATE = as.Date(ham$DATE)

sapply(ham, class)
str(ham)
ham$Perc = ham$POS_TESTS/ham$TOTAL_TESTS * 100

ggplot(data = ham, aes(x = DATE, y = Perc), lwd=2) + geom_line(color= 'red') + theme(axis.text.x = element_text(angle = 90), legend.direction = 'horizontal', legend.position = 'bottom')  + scale_x_date(date_labels="%b %d",date_breaks  ="1 week") + ggtitle("Percent of Tests Positive in Hamilton County") + ylab("% Positive Tests") + ylim(4,10)

ggplot(data = ham, aes(x = DATE, y = 100-Perc), lwd=2) + geom_line(color= 'red') + theme(axis.text.x = element_text(angle = 90), legend.direction = 'horizontal', legend.position = 'bottom')  + scale_x_date(date_labels="%b %d",date_breaks  ="1 week") + ggtitle("Percent of Tests Negative in Hamilton County") + ylab("Percent of Tests Reported Negative")

```

```{r}
ggplot(data = ham) + geom_line(aes(x = DATE, y = NEG_TESTS, color = 'green'), lwd=2) + geom_line(aes(x = DATE, y = TOTAL_TESTS, color = 'blue'), lwd=2) + theme(axis.text.x = element_text(angle = 90))  + geom_line(aes(x = DATE, y = POS_TESTS, color = 'red'), lwd=2) + scale_x_date(date_labels="%b %d",date_breaks  ="1 week") + ggtitle("Hamilton County Testing") + ylab("Tests") + scale_color_discrete(name = "Testing", labels = c("Positive", "Negative", "Total"))
```

```{r}

test = ham[,c("POS_TESTS","TOTAL_TESTS")]
test1 = cor(test)

library(Hmisc)
test2 = rcorr(as.matrix(test), type = c("pearson","spearman"))

flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}

flattenCorrMatrix(test2$r, test2$P)

library(corrplot)
corrplot(test1, type = "upper", order = "hclust", 
         tl.col = "black")

corrplot(test1, type="upper", order="hclust", 
         p.mat = test2$P, sig.level = 0.01, insig = "blank")
```

```{r}

library("PerformanceAnalytics")
chart.Correlation(test, histogram=TRUE, pch=19)
```

```{r}
# zipmerge$CasesbyMinor = zipmerge$CAT_TOTALCASES/zipmerge$X2019.Minority.Population
png("../Visualization/PercHispanic.png", width=7,height=4,units='in', res=600,bg = 'transparent')

zipmerge$HispPerc = zipmerge$X2019.Minority.Population/zipmerge$X2019.Total.Population
topten = top_n(zipmerge, 10, CAT_TOTALCASES)
ggplot(data = topten, aes(x=HispPerc,y=CAT_TOTALCASES,color= CAT_DETAIL)) + geom_point() +theme(axis.text.x = element_text(angle = 90)) + ylab("Total Cases by ZipCode") + xlab("Percent of Population Hispanic") +xlim(0,1) + ggtitle("Ten Highest Case Zipcodes by Percent Hispanic")
dev.off()
```

```{r}
png("../Visualization/PercHispanicTopTenHisp.png", width=7,height=4,units='in', res=600,bg = 'transparent')

zipmerge$HispPerc = zipmerge$X2019.Minority.Population/zipmerge$X2019.Total.Population
topten = top_n(zipmerge, 10, HispPerc)
ggplot(data = topten, aes(x=HispPerc,y=CAT_TOTALCASES,color= CAT_DETAIL)) + geom_point() +theme(axis.text.x = element_text(angle = 90)) + ylab("Total Cases by ZipCode") + xlab("Percent of Population Hispanic") +xlim(0,1) + ggtitle("Ten Highest Percent Hispanic")
dev.off()
```

```{r}
zipmerge$BlackPerc = zipmerge$X2019.Black.Population/zipmerge$X2019.Total.Population
topten = top_n(zipmerge, 10, CAT_TOTALCASES)
png("../Visualization/PercBlack.png", width=7,height=4,units='in', res=600,bg = 'transparent')

ggplot(data = topten, aes(x=BlackPerc,y=CAT_TOTALCASES,color= CAT_DETAIL)) + geom_point() +theme(axis.text.x = element_text(angle = 90)) + ylab("Total Cases by ZipCode") + xlab("Percent of Population Black") +xlim(0,1) + ggtitle("Ten Highest Case Zipcodes by Percent Black")
dev.off()
```

```{r}
topten = top_n(zipmerge, 10, BlackPerc)
png("../Visualization/PercBlackTopTenBlack.png", width=7,height=4,units='in', res=600,bg = 'transparent')

ggplot(data = topten, aes(x=BlackPerc,y=CAT_TOTALCASES,color= CAT_DETAIL)) + geom_point() +theme(axis.text.x = element_text(angle = 90)) + ylab("Total Cases by ZipCode") + xlab("Percent of Population Black") +xlim(0,1) + ggtitle("Ten Highest Percent Black")
dev.off()
```

```{r}
zipmerge$WhitePerc = zipmerge$X2019.White.Population/zipmerge$X2019.Total.Population
topten = top_n(zipmerge, 10, CAT_TOTALCASES)
png("../Visualization/PercWhite.png", width=7,height=4,units='in', res=600,bg = 'transparent')

ggplot(data = topten, aes(x=WhitePerc,y=CAT_TOTALCASES,color= CAT_DETAIL)) + geom_point() +theme(axis.text.x = element_text(angle = 90)) + ylab("Total Cases by ZipCode") + xlab("Percent of Population White") +xlim(0,1) + ggtitle("Ten Highest Case Zipcodes by Percent White")
dev.off()
```

```{r}
zipmerge$MinPerc = zipmerge$X2019.Minority.Population/zipmerge$X2019.Total.Population
topten = top_n(zipmerge, 10, CAT_TOTALCASES)
png("../Visualization/PercMinority.png", width=7,height=4,units='in', res=600,bg = 'transparent')
ggplot(data = topten, aes(x=MinPerc,y=CAT_TOTALCASES,color= CAT_DETAIL)) + geom_point() +theme(axis.text.x = element_text(angle = 90)) + ylab("Total Cases by ZipCode") + xlab("Percent of Population Minority") +xlim(0,1) + ggtitle("Ten Highest Case Zipcodes by Percent Minority")
dev.off()
```

```{r}
# zipmerge$MinPerc = zipmerge$X2019.Minority.Population/zipmerge$X2019.Total.Population
topten = top_n(zipmerge, 10, MinPerc)
png("../Visualization/PercMinorityTopTenMinPerc.png", width=7,height=4,units='in', res=600,bg = 'transparent')
ggplot(data = topten, aes(x=MinPerc,y=CAT_TOTALCASES,color= CAT_DETAIL)) + geom_point() +theme(axis.text.x = element_text(angle = 90)) + ylab("Total Cases by ZipCode") + xlab("Percent of Population Minority") +xlim(0,1) + ggtitle("Ten Highest Percent Minority")
dev.off()
```


```{r}
library(ggplot2)
zipmerge$CAT_TOTALCASESPERCENT = gsub( "%", "", as.character(zipmerge$CAT_TOTALCASESPERCENT))
zipmerge$CAT_TOTALCASESPERCENT = as.numeric(zipmerge$CAT_TOTALCASESPERCENT)
nonzero = zipmerge[which(zipmerge$CAT_TOTALCASESPERCENT > 0),]
# png("../Visualization/PercofTotalbyZipcode.png", width=1080,height=680,units='px',res=200, bg = 'transparent')
ggplot(data = nonzero) + geom_bar(aes(y=CAT_TOTALCASESPERCENT,x=reorder(CAT_DETAIL, -CAT_TOTALCASESPERCENT), fill = CAT_DETAIL),position="dodge", stat="identity") + theme(axis.text.x = element_text(angle = 90), legend.position = "none") + ylab("Percent of Total County Cases") + xlab("") + ylim(0,30) + scale_fill_discrete(name = "") + ggtitle("Percent of County Total Cases by Zipcode")
# dev.off()
# ggsave(
#   "../Visualization/PercofTotalbyZipcode.png",
#   plot,
#   width = 8,
#   height = 4.4,
#   dpi = 1200
# )
```

```{r}
topten = top_n(zipmerge, 10, CAT_TOTALCASES)
ggplot(data = topten) + geom_bar(aes(y=CAT_TOTALCASESPERCENT,x=reorder(CAT_DETAIL, -CAT_TOTALCASESPERCENT), fill = CAT_DETAIL),position="dodge", stat="identity") + theme(axis.text.x = element_text(angle = 90),legend.position = "none") + ylab("Percent of Total County Cases") + xlab("Zipcode") + scale_fill_discrete(name = "Zipcode")
```

```{r}
zipmerge$PopbyThou = zipmerge$Total.Population/1000
zipmerge$CasebyThou = zipmerge$CAT_TOTALCASES/zipmerge$PopbyThou
```

```{r}
ggplot(data = zipmerge) + geom_bar(aes(y=CasebyThou,x=reorder(CAT_DETAIL, -CasebyThou), fill = CAT_DETAIL),position="dodge", stat="identity") + theme(axis.text.x = element_text(angle = 90),legend.position = "none") + ylab("Cases per Thousand Residents") + xlab("Zipcode") + scale_fill_discrete(name = "Zipcode") + ggtitle("COVID-19 Cases per Thousand Residents by Zip Code - May 27, 2020")
```

```{r}
colnames(zipmerge)
```


```{r}
zipmerge$CAT_TOTALCASESPERCENT = zipmerge$CAT_TOTALCASES / sum(zipmerge$CAT_TOTALCASES)
ggplot(data=zipmerge) + geom_point(aes(x=Hispanic.Percent, y=CAT_TOTALCASESPERCENT, color = CAT_DETAIL)) + xlim(0,100)

ggplot(data=zipmerge) + geom_point(aes(x=White.Percent, y=CAT_TOTALCASESPERCENT, color = CAT_DETAIL)) + xlim(0,100)

ggplot(data=zipmerge) + geom_point(aes(x=Black.Percent, y=CAT_TOTALCASESPERCENT, color = CAT_DETAIL)) + xlim(0,100)

ggplot(data=zipmerge) + geom_point(aes(x=Median.Household.Income, y=CAT_TOTALCASESPERCENT, color = CAT_DETAIL)) +theme(axis.text.x = element_text(angle = 90)) + ylab("Total Cases by ZipCode") + xlab("Percent of Population Minority") +xlim(0,1) + ggtitle("Ten Highest Case Zipcodes by Percent Minority")
```

```{r}
ethrace = rbind(Ethnicity, Race)
ethrace = ethrace[which(!ethrace$CAT_DETAIL == 'Pending'),]

ethrace = ethrace[complete.cases(ethrace$CAT_TOTALCASES),]
pops = zipmerge[,sapply(zipmerge, is.numeric)]
pops = as.data.frame(sapply(pops, sum))
pops = t(pops)
colnames(pops)
drop = c("OBJECTID", "GEOID10","ALAND10","AWATER10","INTPTLAT10","INTPTLON10","Shape_Length"                ,"Shape_Area")
pops = as.data.frame(pops[!names(pops) %in% drop])
# ethrace$CasebyPop = 
```

```{r}
ggplot(data = zipmerge) + geom_bar(aes(y=CAT_TOTALCASESPERCENT*100,x=reorder(CAT_DETAIL, -CAT_TOTALCASESPERCENT), fill = CAT_DETAIL),position="dodge", stat="identity") + theme(axis.text.x = element_text(angle = 90),legend.position = "none") + ylab("Percent of Hamilton County Cases") + xlab("Zipcode") + scale_fill_discrete(name = "Zipcode") + ggtitle("Percent Hamilton County COVID-19 Cases by Zip Code - May 27, 2020")
```

```{r}
library(ggplot2)
library(ggmap)
zipmerge = st_as_sf(zipmerge)

box = st_bbox(zipmerge)
box

bb<- make_bbox(lat=c(box['ymin'],box['ymax']),lon=c(box['xmin'],box['xmax']), f=0.05)
bb
zoomed = calc_zoom(bb)
zoomed
# register_google("AIzaSyCdi7_sZmNl3ost3hiex_IplIDS-WP1QHM")
cda<-get_map(bb,zoom=zoomed,maptype="roadmap", source='google')


daterange = sort(unique(zipmerge$DATE))
for (date in daterange){
  casedata = zipmerge[which(zipmerge$DATE == date),]
  plotmap = ggmap(cda)  + coord_sf(crs = st_crs(casedata)) + geom_sf(data=casedata, aes(fill=CAT_CASES_TOTAL_PER1K), inherit.aes = FALSE)  + ggtitle(paste("COVID Data for ", date, sep="")) + scale_fill_gradient2(low = "blue", high = "red",mid = "yellow",midpoint = 13, "Case per 1K", limits=c(0,25)) + xlab("Longitude") + ylab("Latitude") + theme(
    legend.position = c(.05, .99),
    legend.justification = c("left", "top"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)
    )
  print(plotmap)
}
```

```{r}
for (date in daterange){
  casedata = zipmerge[which(zipmerge$DATE == date),]
  plotmap = ggmap(cda)  + coord_sf(crs = st_crs(casedata)) + geom_sf(data=casedata, aes(fill=CAT_CASES_TOTAL), inherit.aes = FALSE)  + ggtitle(paste("COVID Data for ", date, sep="")) + scale_fill_gradient2(low = "blue", high = "red",mid = "yellow",midpoint = 110, "Cases per Zip", limits=c(0,220)) + xlab("Longitude") + ylab("Latitude") + theme(
    legend.position = c(.05, .99),
    legend.justification = c("left", "top"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)
    )
  print(plotmap)
}
```

```{r}
zipmerge$CAT_CASES_TOTAL_PERCENT = as.numeric(zipmerge$CAT_CASES_TOTAL_PERCENT)
for (date in daterange){
  print(date)
  casedata = zipmerge[which(zipmerge$DATE == date),]
  
  # print(typeof(casedata$CAT_CASES_TOTAL_PERCENT))
  plotmap = ggmap(cda)  + coord_sf(crs = st_crs(casedata)) + geom_sf(data=casedata, aes(fill=CAT_CASES_TOTAL_PERCENT), inherit.aes = FALSE) + scale_fill_gradient2(low = "blue", high = "red",mid = "yellow",midpoint = 15.00, "% County Total", limits=c(0,30.00)) + xlab("Longitude") + ylab("Latitude") + theme(
    legend.position = c(.05, .99),
    legend.justification = c("left", "top"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6))
  print(plotmap)
}
```

```{r}
library(ggplot2)
library(ggmap)
library(gganimate)
library(sf)
library(st)

  plotmap = ggmap(cda)  + coord_sf(crs = st_crs(zipmerge)) + geom_sf(data=zipmerge, aes(fill=CAT_CASES_TOTAL, frame = DATE), inherit.aes = FALSE) + scale_fill_gradient2(low = "blue", high = "red",mid = "yellow",midpoint = 110, "Cases by Zip", limits=c(0,220)) + xlab("Longitude") + ylab("Latitude") + theme(plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey"),
    legend.position = c(.05, .99),
    legend.justification = c("left", "top"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)) + transition_states(DATE, transition_length = 2, state_length = 5, wrap = FALSE) + labs(title = 'COVID Cases : {closest_state}')

plotmap

animate(plotmap, 100, fps = 20,  width = 900, height = 600, end_pause=20,
        renderer = gifski_renderer("../ZipTotals.gif"))

```

```{r}
library(ggplot2)
library(ggmap)
library(gganimate)
library(sf)
library(st)

  plotmap = ggmap(cda)  + coord_sf(crs = st_crs(zipmerge)) + geom_sf(data=zipmerge, aes(fill=CAT_CASES_TOTAL_PER1K, frame = DATE), inherit.aes = FALSE) + scale_fill_gradient2(low = "blue", high = "red",mid = "yellow",midpoint = 13, "Cases per 1K", limits=c(0,25)) + xlab("Longitude") + ylab("Latitude") + theme(plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey"),
    legend.position = c(.05, .99),
    legend.justification = c("left", "top"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)) + transition_states(DATE, transition_length = 2, state_length = 5, wrap = FALSE) + labs(title = 'COVID Cases per 1K : {closest_state}')

plotmap

animate(plotmap, 100, fps = 20,  width = 900, height = 600, end_pause=20,
        renderer = gifski_renderer("../Per1K.gif"))

```

```{r}
library(ggplot2)
library(ggmap)
library(gganimate)
library(sf)
library(st)

  plotmap = ggmap(cda)  + coord_sf(crs = st_crs(zipmerge)) + geom_sf(data=zipmerge, aes(fill=CAT_CASES_TOTAL_PERCENT, frame = DATE), inherit.aes = FALSE) + scale_fill_gradient2(low = "blue", high = "red",mid = "yellow",midpoint = 15.00, "% County Total", limits=c(0,30.00)) + xlab("Longitude") + ylab("Latitude") + theme(plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey"),
    legend.position = c(.05, .99),
    legend.justification = c("left", "top"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)) + transition_states(DATE, transition_length = 2, state_length = 5, wrap = FALSE) + labs(title = 'Percent of Hamilton County Cases : {closest_state}')

plotmap

animate(plotmap, 100, fps = 20,  width = 900, height = 600, end_pause=20,
        renderer = gifski_renderer("../PercCountyTotal.gif"))

```

